from .rotor import Rotor

ROTOR_BETA = Rotor("LEYJVCNIXWPBQMDRTAKZGFUHOS")
ROTOR_GAMMA = Rotor("FSOKANUERHMBTIYCWLQPZXVGJD")

ROTOR_I = Rotor("EKMFLGDQVZNTOWYHXUSPAIBRCJ", "Q")
ROTOR_II = Rotor("AJDKSIRUXBLHWTMCQGZNPYFVOE", "E")
ROTOR_III = Rotor("BDFHJLCPRTXVZNYEIWGAKMUSQO", "V")
ROTOR_IV = Rotor("ESOVPZJAYQUIRHXLNFTGKDCMWB", "J")
ROTOR_V = Rotor("VZBRGITYUPSDNHLXAWMJQOFECK", "Z")

ROTOR_A = Rotor("EJMZALYXVBWFCRQUONTSPIKHGD")
ROTOR_B = Rotor("YRUHQSLDPXNGOKMIEBFZCWVJAT")
ROTOR_C = Rotor("FVPJIAOYEDRZXWGCTKUQSBNMHL")
